# Generated by Django 5.2.6 on 2025-11-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatedata',
            options={'verbose_name': '気候データ', 'verbose_name_plural': '気候データ'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': '指標', 'verbose_name_plural': '指標マスター'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '地域', 'verbose_name_plural': '地域マスター'},
        ),
        migrations.AlterField(
            model_name='region',
            name='iso_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
