# Generated by Django 5.2.6 on 2025-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0002_alter_climatedata_options_alter_indicator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='metadata_url',
            field=models.URLField(blank=True),
        ),
    ]
