# Generated by Django 5.2.6 on 2025-11-09 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_data', '0003_indicator_metadata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2200)]),
        ),
    ]
